### ISSUE TITLE
Include a free-threaded PEP703 build in the releases page

### ISSUE THREAD

**Issue by tonybaloney** [python/cpython#112430]
# Feature or enhancement

### Proposal:

Will the next CPython 3.13 releases (alpha 3) include a set of builds that have `--disable-gil` set?

I'm looking at how free-threaded builds can be tested in CI workflows and the solutions all involve compiling from source with the flags then caching the binaries. It would be a lot easier if the CPython release builds included a free-threaded variant that folks can download. Especially for Windows (because it requires a lot of extra software) and macOS because of the signing requirements. 

Related: https://github.com/actions/setup-python/issues/771

CC @hugovk 

### Has this already been discussed elsewhere?

No response given

**Comment by tonybaloney** [comment]
Question mainly for the Python 3.13 release manager (@Yhg1s )

**Comment by hugovk** [comment]
cc @colesbury, and also @zooba for Windows and @ned-deily and macOS.

---

If you want to test _Ubuntu_ via GitHub Actions, as of [yesterday](https://github.com/deadsnakes/action/pull/123) you can use https://github.com/deadsnakes/action with `nogil: true`:

```yml
    - name: Set up Python ${{ matrix.python-version }}
      if: endsWith(matrix.python-version, '-dev')
      uses: deadsnakes/action@v3.1.0
      with:
        python-version: ${{ matrix.python-version }}
        nogil: true
```

This uses the deadsnakes PPA which already had `--disable-gil` builds available. For example, see python3.13-nogil under "python3.13 - 3.13.0~a1-1+jammy2" at https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+packages

(It's still a bit early to test, and we're also pending https://github.com/pypa/packaging and wheel releases for the `cp313t` wheel tag.)
