### ISSUE TITLE
Floating point syntax specification is incorrect

### ISSUE THREAD

**Issue by knotapun** [python/cpython#114070]
# Documentation

The floating point syntax spec is incorrect, and can be found in [/Doc/library/functions.rst](https://github.com/python/cpython/blob/main/Doc/library/functions.rst):

The syntax [rendered currently](https://docs.python.org/3/library/functions.html#float) is the following:

```ebnf
sign        ::=  "+" | "-"
infinity    ::=  "Infinity" | "inf"
nan         ::=  "nan"
digitpart   ::=  `!digit` (["_"] `!digit`)* 
number      ::=  [digitpart] "." digitpart | digitpart ["."]
exponent    ::=  ("e" | "E") ["+" | "-"] digitpart
floatnumber ::=  number [exponent]
floatvalue  ::=  [sign] (floatnumber | infinity | nan)
```
`digitpart` should not include an exclamation point or backtick quotes. The backticks appear to be the underlying syntax failing to render, but the exclamation points have a meaning, which is an issue. This is the underlying syntax:

```yaml
sign: "+" | "-"
infinity: "Infinity" | "inf"
nan: "nan"
digitpart: `!digit` (["_"] `!digit`)*
number: [`digitpart`] "." `digitpart` | `digitpart` ["."]
exponent: ("e" | "E") ["+" | "-"] `digitpart`
floatnumber: number [`exponent`]
```

EBNF includes a "[Special Sequences](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form#Table_of_symbols)" syntax, that would be appropriate for this situation, but I'm uncertain if it is possible to use in the underlying YAML format. It should be rendered like this:

```ebnf
sign        ::=  "+" | "-"
infinity    ::=  "Infinity" | "inf"
nan         ::=  "nan"
digit       ::=  ? Any character in the unicode digit class ?
digitpart   ::=  digit (["_"] digit)* 
number      ::=  [digitpart] "." digitpart | digitpart ["."]
exponent    ::=  ("e" | "E") ["+" | "-"] digitpart
floatnumber ::=  number [exponent]
floatvalue  ::=  [sign] (floatnumber | infinity | nan)
```

### Linked PRs
* gh-114080
* gh-114094
* gh-114095
* gh-114169
* gh-114192
* gh-114193
