### ISSUE TITLE
Cirrus M1 macOS runners never start on fork

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120111]
The Cirrus M1 macOS runners introduced in #119979 never start on [my fork](https://github.com/nineteendo/cpython/actions/runs/9371716405/job/25801596396). This causes every workflow to fail. Can we skip this job in that case?

### Linked PRs
* gh-120116
* gh-120152
* gh-120153

**Comment by hugovk** [comment]
Yes, does something like this in `.github/workflows/reusable-macos.yml` work?

```yml
  build_macos:
    name: 'build and test'
    if: |
      github.repository_owner != 'python'
      && matrix.os == 'ghcr.io/cirruslabs/macos-runner:sonoma'
```

**Comment by nineteendo** [comment]
Didn't work.

**Comment by nineteendo** [comment]
Currently trying this:

```yaml
      matrix:
        os: ${{fromJson(inputs.os-matrix)}}
        isFork: ${{ github.repository_owner != 'python' }}
        exclude:
          - isFork: true
            os: 'ghcr.io/cirruslabs/macos-runner:sonoma'
```
