### ISSUE TITLE
Improve and maintain `Doc/data/refcounts.dat`

### ISSUE THREAD

**Issue by picnixz** [python/cpython#127443]
The `Doc/data/refcounts.dat` file is sometimes updated and sometimes not. I suggest we try to make it up-to-date as much as possible, at least by adding the functions part of the stable ABI.

In addition, the entries are not sorted alphabetically. While they are semantically sorted, it does not help when adding new entries (where should we put it?). So I suggest to reformat the file once I'm done with adding the new entries. 

Finally, I suggest adding a small script that checks whether the file is up-to-date, at least by checking whether the stable ABI is a subset of that file and whether the refcounts.dat is sorted or not (again it will be part of a CI workflow).

The main motivation behind this is to help newcomers in understanding whether a reference is borrowed or not (sometimes the comment doesn't say anything). It could also help in managing a future linter. Note that we have no syntax to indicate whether a reference is stolen or not so we should also improve that part.

cc @vstinner @encukou @Eclips4 @ZeroIntensity 

### Linked PRs
* gh-127444
* gh-127451
* gh-127496
* gh-127497
* gh-127468
* gh-127476

```[tasklist]
### Tasks
- [x] Add refcounts entries from the stable ABI (only func entries)
- [x] Allow to specify when a reference is stolen (use "$" instead of "0")
- [x] Add a script for checking whether the file is correctly formatted (check order, syntax, but not advanced format)
- [x] Add a script for checking if the file is up-to-date when a new function is added to the Stable ABI
- [ ] Unify format (sort entries, add blank lines, add space before pointer dereference marker (optional, likely not))
- [ ] Add CI jobs
- [ ] Use a script to auto-generate the refcounts.dat and let the developer fill out the entries
```

**Comment by ZeroIntensity** [comment]
I think it's worth trying to maintain this for all of the public C API, not just the stable ABI. If the goal is to design a static analyzer, then it would be ideal to have everything.

**Comment by picnixz** [comment]
> I think it's worth trying to maintain this for all of the public C API, not just the stable ABI. If the goal is to design a static analyzer, then it would be ideal to have everything.

Yes, but I'd like to start with the stable ABI for now. It was quite simple to extract the diff but in order to extract all the exported functions and make the diff, I think my one-liner will be a bit too long...

**Comment by picnixz** [comment]
Ok, so having an autoformatter may be a bit tricky. I really don't want to create a C parser just to parse the type declaration. I think I'll just manually change them with some powerful regexes and that's it. But for now, I'll just wait for the other PRs to land before changing them. (Anyway, at some point I'll need to sort the file alphabetically, and the diff won't really matter :D)

**Comment by tomasr8** [comment]
> I really don't want to create a C parser just to parse the type declaration.

I've never used it so I don't know what the current status is, but there is a C parser under `Tools/c-analyzer/c_parser`. Might also be a good starting point if we decide to add a proper static analyzer at some point..

**Comment by picnixz** [comment]
Yes, but I felt it would have been an overkill to use that one actually. I just wanted a simplest parser for declarations without the rest.

**Comment by picnixz** [comment]
@ZeroIntensity For the TOML conversion, we have some limitations. We need to quote '$' and 'null' if they appear and we need to use either inline tables or inline arrays to reduce the size of the file IMO. Instead, I suggest to always create a top-level section per function:

```toml
[$funcname$]
```

We can add "deprecated" and "comment" to that top-level section, helping the newcomers.

Followed by the the return section:

```toml
[$funcname$.return]
ctype = "PyObject *"
refdelta = 1
# or for functions that always return NULL
[$funcname$.return]
ctype = "PyObject *"
idempotent = true
```

And finally by the section for the parameters, here's an example:

```toml
[$funcname$.params.a]
ctype = "PyObject *"
steals = true
[$funcname$.params.b]
ctype = "PyObject *"
refdelta = 1
[$funcname$.params.c]
ctype = "PyObject *"
refdelta = -1
[$funcname$.params.d]
ctype = "PyObject *"
refdelta = 0
[$funcname$.params.e]
ctype = "const char *"
``` 

Each section will always have an optional "comment" key. For instance:

```
PyBytes_AS_STRING:char*:::
PyBytes_AS_STRING:PyObject*:string:0:
```

becomes

```toml
[PyBytes_AS_STRING]
[PyBytes_AS_STRING.return]
ctype = "char *"
[PyBytes_AS_STRING.params.string]
ctype = "PyObject *"
refdelta = 0
```

We can also compress it into:

```toml
[PyBytes_AS_STRING]
return.ctype = "char *"
params.string.ctype = "PyObject *"
params.string.refdelta = 0
```

wDYT?

**Comment by ZeroIntensity** [comment]
I'm not all that worried about compression--it's going to be a big file any way we do it. I think we should use an array of tables for the parameters instead of trying to create new keys for each parameter (it's significantly easier to parse it back into Python that way). For reference, the TOML I generated ended up looking like this:

```toml

[PyArg_Parse]
name = "PyArg_Parse"
return_type = "int"

[[PyArg_Parse.args]]
name = "args"
type = "PyObject *"
effect = 0

[[PyArg_Parse.args]]
name = "format"
type = "const char *"

[[PyArg_Parse.args]]
name = "..."
type = "ellipsis"
```

I'm not sure how we should denote some weird things like "always NULL" though. Special boolean flags like `always_null = true` or `steal = true` look pretty, but they'll pile up weirdly over time.

**Comment by ZeroIntensity** [comment]
An array rather than a mapping for what?

**Comment by picnixz** [comment]
For the list of parameters. My first suggestion was using a mapping where the key is the parameter name:

```toml
[PyBytes_AS_STRING.params.string]
ctype = "PyObject *"
refdelta = 0
```

but for you, it would be:

```toml
[[PyArg_Parse.params]]
name = "string
ctype = "PyObject *"
refdelta = 0
```
