### ISSUE TITLE
Simple extension module in C sets `errno=2` somewhere

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#129606]
# Bug report

Reproduction:

```c
// asm_builtins/mod.c
#include <Python.h>

static PyObject *
print(PyObject *self, PyObject *args)
{
    Py_RETURN_NONE;
}

PyDoc_STRVAR(print__doc__,
"print($module, /, *args)\n"
"--\n"
"\n"
"Print passed args as strings.");


static PyMethodDef module_methods[] = {
    {"print", (PyCFunction)print, METH_VARARGS, print__doc__},
    {NULL}  // sentinel
};


static struct PyModuleDef asm_builtins_spec = {
    PyModuleDef_HEAD_INIT,
    "asm_builtins",
    PyDoc_STR("Builtins re-implemented in ASM"),
    -1,
    module_methods
};


PyMODINIT_FUNC PyInit_asm_builtins(void) {
    printf("errno = %d\n", errno);  // this will print `errno=2`
    return PyModule_Create(&asm_builtins_spec);
}
```
I created a repro here: https://github.com/sobolevn/errno-2-repro

You can see that all actions with Python versions from 3.9 to 3.13 print the same `errno` on Linux (tested on macos as well - the same).

But, other than that - there are no exceptions / failures / bugs / etc. Everything works.

Is it a bug? Or am I missing something obvious?

**Comment by skirpichev** [comment]
Does it happened for you locally?  I tried this demo and `import asm_builtins` indeed prints errno=2.

On another hand, with simple `pyproject.toml`:
```toml
[build-system]
requires = ["setuptools>=74.1"]
build-backend = "setuptools.build_meta"

[project]
name = "asm_builtins"
version = "0.0.1"

[tool.setuptools]
ext-modules = [{name = "asm_builtins", sources = ["mod.c"]}] # mod.c - literally your source
```
I got errno=0.  Same with [my extension](https://github.com/diofant/python-gmp).  Using setuptools-75.8.0.
