### ISSUE TITLE
Add a docker compose configuration file

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#135693]
As suggested by @malemburg in https://discuss.python.org/t/what-do-people-want-to-see-to-make-supporting-wasi-easier/94472/ , we could add a `.devcontainer/compose.yml` file to provide another way to get the [dev container](https://github.com/python/cpython-devcontainers/) beyond the [instructions in the devguide](https://devguide.python.org/getting-started/setup-building/#building-the-container-locally) (which I'm [improving](https://github.com/python/devguide/pull/1581)). It would probably be something along the lines of:

```yaml
# Start: docker compose --file .devcontainer/compose.yml up --detach
# Get a shell: docker compose exec cpython-dev bash
# Stop: docker compose down
# Cleanup: docker compose rm cpython-dev
services:
  cpython-dev:
    image: ghcr.io/python/devcontainer:latest
    container_name: cpython-dev
    restart: unless-stopped
    entrypoint: sleep 86400
    working_dir: /workspace
    volumes:
      - ../:/workspace
```

The biggest benefit I can see from other approaches to using the image outside of GitHub Codespaces like `docker run` is you don't need to know where the container registry is to get going.

**Comment by brettcannon** [comment]
And if you want an out-of-tree config extending the config above:

```yml
services:
  out-of-tree:
    extends:
      file: compose.yml
      service: cpython-dev
    working_dir: /build
    volumes:
    - ../../build:/build
    - ../:/workspace:ro
```

The problem with this is if `../../build` doesn't exist then it creates it as root when `docker compose up` runs.
